FROM node:10

WORKDIR /usr/src/app

COPY . .

ARG SERVICE_NODE_API_PORT
ENV SERVICE_NODE_API_PORT $SERVICE_NODE_API_PORT

ARG GETH_RPC_PORT
ENV GETH_RPC_PORT $GETH_RPC_PORT

EXPOSE $SERVICE_NODE_API_PORT
EXPOSE $GETH_RPC_PORT

CMD ["npm", "run", "start"]
