export enum FileUploadingStage {
    DDS_UPLOAD = "DDS_UPLOAD",
    BILLING_PROCESSING = "BILLING_PROCESSING",
    DDS_PAYMENT_NOTIFICATION = "DDS_PAYMENT_NOTIFICATION",
    LOCAL_FILE_STATUS_UPDATE = "LOCAL_FILE_STATUS_UPDATE"
}
